services:
  frontend:
    build: ./gestiondocumento
    ports:
      - "5173:5173"
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend/src/infrastructure:/app/backend/src/infrastructure
  converter:
    build: ./convertpdf
    ports:
      - "5000:5000"
